# Generated by Django 5.1.5 on 2025-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ad_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
