# Generated by Django 5.1.5 on 2025-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='Нет номера', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
