# Generated by Django 5.1.5 on 2025-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
