# Generated by Django 5.1.5 on 2025-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_customuser_city_customuser_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
