# Generated by Django 5.1.5 on 2025-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_ad_image_adimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.DeleteModel(
            name='AdImage',
        ),
    ]
