# Generated by Django 5.1.5 on 2025-03-26 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_ad_city_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='createdimage',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/'),
        ),
    ]
