# Generated by Django 5.1.5 on 2025-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(default='Договірна', max_length=10),
        ),
    ]
