# Generated by Django 5.1.5 on 2025-03-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_remove_ad_image_alter_adimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='createdimage',
        ),
    ]
