# Generated by Django 5.1.5 on 2025-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_ad_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
