# Generated by Django 5.1.5 on 2025-04-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_ad_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='premium_until',
        ),
    ]
